import { AbsoluteFill, spring, useCurrentFrame, useVideoConfig } from "remotion";
const scenes = [
  { start: 0, end: 6, kicker: "你已经离开那家公司了", title: "为什么身体还在上班？", body: "有些职场经历结束了，警报却没有结束。" },
  { start: 6, end: 18, kicker: "它可能来自", title: "长期羞辱、霸凌、威胁", body: "也可能来自过劳、失控的管理、重大事故，或一次让你彻底崩溃的事件。" },
  { start: 18, end: 32, kicker: "创伤后的大脑会", title: "把办公室记成危险现场", body: "一封邮件、一个铃声、一句“方便聊聊吗”，都可能让心跳突然加速。" },
  { start: 32, end: 48, kicker: "常见信号", title: "不是你太脆弱", body: "反复回想、做噩梦、失眠、惊跳、易怒；回避会议，也不敢再相信同事。" },
  { start: 48, end: 61, kicker: "它和普通疲惫不同", title: "休息一晚，警报不会自动关闭", body: "倦怠更像“被耗尽”，创伤后应激则像“危险还在发生”。两者也可能同时出现。" },
  { start: 61, end: 76, kicker: "先做三件小事", title: "把现在，和当时分开", body: "说出你看见的五样东西；让呼吸慢下来；把触发你的场景和感受记下来。" },
  { start: 76, end: 90, kicker: "请记住", title: "求助不是认输", body: "如果症状持续数周、影响睡眠和工作，请找心理治疗师或精神科医生。你不必一个人扛。" },
];
export const EPISODE03_DURATION = 90 * 30;
export const Episode03 = () => { const frame = useCurrentFrame(); const { fps } = useVideoConfig(); const seconds = frame / fps; const scene = scenes.find((item) => seconds >= item.start && seconds < item.end) ?? scenes[scenes.length - 1]; const enter = spring({ frame: Math.min(frame - scene.start * fps, 18), fps, config: { damping: 16, stiffness: 120 } }); const progress = (seconds / 90) * 100; return <AbsoluteFill style={{ background: "#101216", color: "#f4f1eb", fontFamily: "Arial, sans-serif", overflow: "hidden" }}><AbsoluteFill style={{ opacity: 0.12, backgroundImage: "linear-gradient(#d8d2c4 1px, transparent 1px), linear-gradient(90deg, #d8d2c4 1px, transparent 1px)", backgroundSize: "72px 72px" }} /><div style={{ position: "absolute", top: 94, left: 70, right: 70, display: "flex", justifyContent: "space-between", color: "#ff6b5f", letterSpacing: 3, fontSize: 22 }}><span>WORK / TRAUMA</span><span>90 SEC</span></div><div style={{ position: "absolute", top: 170, left: 70, width: 120, height: 8, background: "#ff6b5f" }} /><div style={{ position: "absolute", top: 290, left: 70, right: 70, transform: `translateY(${(1 - enter) * 45}px)`, opacity: enter }}><div style={{ color: "#ff8d83", fontSize: 28, letterSpacing: 4, marginBottom: 30 }}>{scene.kicker}</div><div style={{ fontSize: 76, lineHeight: 1.12, fontWeight: 700, maxWidth: 900 }}>{scene.title}</div><div style={{ marginTop: 44, fontSize: 34, lineHeight: 1.55, color: "#c5c1bb", maxWidth: 880 }}>{scene.body}</div></div><div style={{ position: "absolute", left: 70, right: 70, bottom: 130 }}><div style={{ height: 2, background: "#3a3d43" }}><div style={{ width: `${progress}%`, height: 2, background: "#ff6b5f" }} /></div><div style={{ marginTop: 18, display: "flex", justifyContent: "space-between", color: "#777b84", fontSize: 20 }}><span>职场的创伤后应激障碍</span><span>{Math.floor(seconds).toString().padStart(2, "0")} / 90</span></div></div></AbsoluteFill>; };
